#!/bin/bash
mkdir -p assets

function wget_ {
    filepath=$1
    url=$2;
    wget -U "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -O "$1" "$2"
    err=$?
    if [[ $err > 0 ]]; then
        echo "Failed with returncode=$err while downloading $url"
    fi
}


wget_ assets/alum-root-1.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/other/heuchera-richardsonii-prairie-alumroot_0608_132544.jpg"
wget_ assets/alum-root-2.jpg "https://gnps.org/wp-content/uploads/bfi_thumb/Heuchera-americana-qx0fprr5ue99jnbbb4i9lbl460lv17b85v3v7c1ssg.jpg"
wget_ assets/bee-balm-1.jpg "https://www.canr.msu.edu/contentAsset/image/5911e9fa-b006-4ae3-9cd8-9ba7bb9012a0/fileAsset/filter/Resize/resize_w/1200"
wget_ assets/bee-balm-2.jpg "https://www.canr.msu.edu/contentAsset/image/008083be-419c-4dd7-8ae1-c2aba5c6c407/fileAsset/filter/Resize/resize_w/1200"
wget_ assets/carex-brevior-1.jpg "https://hoffmannursery.com/assets/files/images/carex-brevior-01.jpg"
wget_ assets/carex-brevior-2.jpg "https://cdn-kocjb.nitrocdn.com/jCEhjcPcDPgQTAaGxXvYrXpsMJocXVFM/assets/images/optimized/rev-756df5b/kb.jniplants.com/wp-content/uploads/2023/01/plains-oval-sedge-carex-brevior-ftimg.jpg"
wget_ assets/carex-sparganoides-1.jpg "http://www.thismia.com/C/Carex_sparganioides1.jpg"
wget_ assets/carex-sparganoides-2.jpg "https://ornamentalgrass.ca/images/carex-sparganioides.jpg"
wget_ assets/carex-sparganoides-3.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd3/carex-sparganioides-0624-8.jpg"
wget_ assets/carex-sparganoides-4.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/grass/carex-sparganioides_0609_160832.jpg"
wget_ assets/carex-sparganoides-5.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/grass/carex-sparganioides-6-16-1.jpg"
wget_ assets/lance-leaf-coreopsis-1.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/yellow/coreopsis-lanceolata-lance-leaved-tickseed_0613_165358.jpg"
wget_ assets/lance-leaf-coreopsis-2.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/yellow/coreopsis-lanceolata-lance-leaved-tickseed_0613_165211.jpg"
wget_ assets/lance-leaf-coreopsis-3.jpg "https://www.canr.msu.edu/contentAsset/image/07c593cb-1fd7-429a-8574-30daebd3aefe/fileAsset/filter/Resize/resize_w/1200"
wget_ assets/lance-leaf-coreopsis-4.jpg "https://www.canr.msu.edu/contentAsset/image/a1d89ddb-f7a9-4c04-90aa-62c25c9d2260/fileAsset/filter/Resize/resize_w/1200"
wget_ assets/lance-leaf-coreopsis-5.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/yellow/coreopsis-lanceolata-lance-leaved-tickseed_0613_165259.jpg"
wget_ assets/lead-plant-1.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/purple/lead-plant_0701_101513.jpg"
wget_ assets/lead-plant-2.jpg "https://www.applewoodseed.com/wp-content/uploads/2016/11/AMCA-1301.jpg"
wget_ assets/new-england-aster-1.png "https://mainenativeplants.org/wp-content/uploads/2020/04/New-England-Aster-Symphyotrichum-novae-angliae.png"
wget_ assets/new-england-aster-2.jpg "https://www.canr.msu.edu/contentAsset/image/d5b7d646-3ad0-44f6-a192-3e8f1b174592/fileAsset/filter/Resize/resize_w/1200"
wget_ assets/new-england-aster-3.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/purple/new-england-aster-100_5155.jpg"
wget_ assets/new-england-aster-4.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/purple/new-england-aster-100_5152.jpg"
wget_ assets/new-england-aster-5.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/purple/symphyotrichum-novae-angliae-new-england-aster_0920_112404.jpg"
wget_ assets/new-england-aster-6.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/purple/symphyotrichum-novae-angliae-new-england-aster_0904_140443.jpg"
wget_ assets/purple-love-grass-1.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/grass/eragrostis-spectabilis_0724_103712.jpg"
wget_ assets/purple-love-grass-2.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/grass/eragrostis-spectabilis_0724_114001.jpg"
wget_ assets/purple-love-grass-3.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd3/eragrostis-spectabilis-15-4.jpg"
wget_ assets/purple-love-grass-4.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/grass/eragrostis-spectabilis_0724_103945.jpg"
wget_ assets/purple-love-grass-5.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/grass/eragrostis-spectabilis_0724_103808.jpg"
wget_ assets/rough-blazing-star-1.jpg "https://www.canr.msu.edu/contentAsset/image/80bcf670-e8de-4c17-8716-e69cc6afd224/fileAsset/filter/Resize/resize_w/1200"
wget_ assets/rough-blazing-star-2.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/purple/rough-blazing-star-0728_085557.jpg"
wget_ assets/rough-blazing-star-3.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/purple/rough-blazing-star_1101_142454.jpg"
wget_ assets/rough-blazing-star-4.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/purple/rough-blazing-star_0822_103728.jpg"
wget_ assets/rough-blazing-star-5.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/purple/rough-blazing-star-100_3756.jpg"
wget_ assets/shrubby-st-john-s-wort-1.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd/hypericum-punctatum-988-6.jpg"
wget_ assets/shrubby-st-john-s-wort-2.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd/hypericum-punctatum-798-2.jpg"
wget_ assets/shrubby-st-john-s-wort-3.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd/hypericum-punctatum-84393-22.jpg"
wget_ assets/shrubby-st-john-s-wort-4.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd/hypericum-punctatum-489238.jpg"
wget_ assets/shrubby-st-john-s-wort-5.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd/hypericum-punctatum-7981.jpg"
wget_ assets/swamp-milkweed-1.jpg "https://www.selectseeds.com/cdn/shop/products/014-2-1000_1000x1000.jpg?v=1687464393"
wget_ assets/three-awned-grass-1.jpg "https://plant-material.com/cdn/shop/products/IMG_5884-min.jpg?v=1664974811"
wget_ assets/three-awned-grass-2.jpg "https://plant-material.com/cdn/shop/products/IMG_5883-min.jpg?v=1664974813"
wget_ assets/three-awned-grass-3.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd3/aristida-purpurea-091416-1.jpg"
wget_ assets/three-awned-grass-4.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd3/aristida-purpurea-091416-7.jpg"
wget_ assets/three-awned-grass-5.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd3/aristida-purpurea-151-1.jpg"
wget_ assets/virginia-mountain-mint-1.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/white/pycnanthemum-virginianum-virginia-mountain-mint_0720_112738.jpg"
wget_ assets/virginia-mountain-mint-2.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/white/pycnanthemum-virginianum-virginia-mountain-mint_1018_155321.jpg"
wget_ assets/virginia-mountain-mint-3.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/white/pycnanthemum-virginianum-virginia-mountain-mint_0528_135856.jpg"
wget_ assets/virginia-mountain-mint-4.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/white/pycnanthemum-virginianum-virginia-mountain-mint_0528_135839.jpg"
wget_ assets/virginia-mountain-mint-5.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/white/virginia-mountain-mint_0919_173419.jpg"
wget_ assets/wild-columbine-1.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/red/red-columbine-100_5130.jpg"
wget_ assets/wild-columbine-2.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/pd/aquilegia-canadensis-28.jpg"
wget_ assets/wild-columbine-3.jpg "https://images.squarespace-cdn.com/content/v1/65e9f518f091b23d734eebe2/96cd511b-6938-49cc-b65d-52a714d4fded/WSP_aquilegia+canadensis_+columbine_+red+columbine__WildSeedProject_%C2%A9+Heather+McCargo-25-smartpreview.jpg?format=2500w"
wget_ assets/wild-columbine-4.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/red/red-columbine-100_5792.jpg"
wget_ assets/wild-columbine-5.jpg "https://www.minnesotawildflowers.info/udata/r9ndp23q/red/aquilegia-canadensis-red-columbine_0423_130045.jpg"
